[package]
name = "revm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "0.6.2"
hex = "0.4.3"
sha3 = "0.10.1"
byte-slice-cast = "1.2.0"
