[package]
name = "revm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethnum = "1.1.1"
hex = "0.4.3"
sha3 = "0.10.1"
rayon = "0.6.0"
